### ISSUE TITLE
`--ignore-errors` and `--max-retries` do nothing against `ConnectionRefusedError`

### ISSUE THREAD

**Issue by malespiaut** [jsvine/waybackpack#68]
Hello,

I've tried Waybackpack, and the Internet Archive sometimes refuses connexions for apparently no reason, as the refused link can be openned in the browser.

I hoped that `--ignore-errors` would help Waybackpack _ignore_ that error; and that `--max-retries` would _retry_ to connect; but to no avail.

Best regards.

**Comment by jsvine** [comment]
Hi @malespiaut, and thanks for your interest in this tool. Are you able to provide a specific command that raises this issue, so that it can be investigated / debugged?

**Comment by rezinkin** [comment]
Getting snapshot pages................../usr/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to web.archive.org:443 (Connection refused - connect(2) for 207.241.237.3:443) (Errno::ECONNREFUSED)
        from /usr/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
        from /usr/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
        from /usr/lib/ruby/3.1.0/socket.rb:137:in `connect'
        from /usr/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
        from /usr/lib/ruby/3.1.0/socket.rb:227:in `each'
        from /usr/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/lib/ruby/3.1.0/net/http.rb:998:in `connect'
        from /usr/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from /usr/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from /usr/lib/ruby/3.1.0/open-uri.rb:323:in `open_http'
        from /usr/lib/ruby/3.1.0/open-uri.rb:741:in `buffer_open'
        from /usr/lib/ruby/3.1.0/open-uri.rb:212:in `block in open_loop'
        from /usr/lib/ruby/3.1.0/open-uri.rb:210:in `catch'
        from /usr/lib/ruby/3.1.0/open-uri.rb:210:in `open_loop'
        from /usr/lib/ruby/3.1.0/open-uri.rb:151:in `open_uri'
        from /usr/lib/ruby/3.1.0/open-uri.rb:721:in `open'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader/archive_api.rb:13:in `get_raw_list_from_api'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:92:in `block in get_all_snapshots_to_consider'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:91:in `times'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:91:in `get_all_snapshots_to_consider'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:105:in `get_file_list_curated'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:164:in `get_file_list_by_timestamp'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:309:in `file_list_by_timestamp'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:192:in `download_files'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/bin/wayback_machine_downloader:72:in `<top (required)>'
        from /usr/local/bin/wayback_machine_downloader:25:in `load'
        from /usr/local/bin/wayback_machine_downloader:25:in `<main>'
/usr/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 207.241.237.3:443 (Errno::ECONNREFUSED)
        from /usr/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
        from /usr/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
        from /usr/lib/ruby/3.1.0/socket.rb:137:in `connect'
        from /usr/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
        from /usr/lib/ruby/3.1.0/socket.rb:227:in `each'
        from /usr/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/lib/ruby/3.1.0/net/http.rb:998:in `connect'
        from /usr/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from /usr/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from /usr/lib/ruby/3.1.0/open-uri.rb:323:in `open_http'
        from /usr/lib/ruby/3.1.0/open-uri.rb:741:in `buffer_open'
        from /usr/lib/ruby/3.1.0/open-uri.rb:212:in `block in open_loop'
        from /usr/lib/ruby/3.1.0/open-uri.rb:210:in `catch'
        from /usr/lib/ruby/3.1.0/open-uri.rb:210:in `open_loop'
        from /usr/lib/ruby/3.1.0/open-uri.rb:151:in `open_uri'
        from /usr/lib/ruby/3.1.0/open-uri.rb:721:in `open'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader/archive_api.rb:13:in `get_raw_list_from_api'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:92:in `block in get_all_snapshots_to_consider'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:91:in `times'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:91:in `get_all_snapshots_to_consider'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:105:in `get_file_list_curated'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:164:in `get_file_list_by_timestamp'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:309:in `file_list_by_timestamp'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:192:in `download_files'
        from /var/lib/gems/3.1.0/gems/wayback_machine_downloader-2.3.1/bin/wayback_machine_downloader:72:in `<top (required)>'
        from /usr/local/bin/wayback_machine_downloader:25:in `load'
        from /usr/local/bin/wayback_machine_downloader:25:in `<main>'
