### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by Hugo-Plissonneau** [jsvine/waybackpack#69]
```
Getting snapshot pagesC:/Ruby32-x64/lib/ruby/3.2.0/open-uri.rb:369:in `open_http': 503 Service Unavailable (OpenURI::HTTPError)
        from C:/Ruby32-x64/lib/ruby/3.2.0/open-uri.rb:760:in `buffer_open'
        from C:/Ruby32-x64/lib/ruby/3.2.0/open-uri.rb:214:in `block in open_loop'
        from C:/Ruby32-x64/lib/ruby/3.2.0/open-uri.rb:212:in `catch'
        from C:/Ruby32-x64/lib/ruby/3.2.0/open-uri.rb:212:in `open_loop'
        from C:/Ruby32-x64/lib/ruby/3.2.0/open-uri.rb:153:in `open_uri'
        from C:/Ruby32-x64/lib/ruby/3.2.0/open-uri.rb:740:in `open'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader/archive_api.rb:13:in `get_raw_list_from_api'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:88:in `get_all_snapshots_to_consider'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:105:in `get_file_list_curated'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:164:in `get_file_list_by_timestamp'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:309:in `file_list_by_timestamp'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wayback_machine_downloader-2.3.1/lib/wayback_machine_downloader.rb:192:in `download_files'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wayback_machine_downloader-2.3.1/bin/wayback_machine_downloader:72:in `<top (required)>'
        from C:/Ruby32-x64/bin/wayback_machine_downloader:32:in `load'
        from C:/Ruby32-x64/bin/wayback_machine_downloader:32:in `<main>'
```

Tried on both Linux (ubuntu) and windows, whenever I try to download a website it shows me this error, any ideas?

**Comment by jsvine** [comment]
Hello, you seem to be using a different project: https://github.com/hartator/wayback-machine-downloader

**Comment by Hugo-Plissonneau** [comment]
Hi, yes actually I tried several and in the confusion posted the wrong code. But I got the message error 503 from this project as well!

**Comment by jsvine** [comment]
What is the specific command (with arguments) you are running?

**Comment by jsvine** [comment]
Strange, that seems to work fine for me. If you're having trouble with the other program as well, there might be an issue with how your internet connection is configured.
